name: CI

on:
  push:
    branches:
      - master

stages:
  - build
  - unit_tests
  - system_test
  - metrics

jobs:
  build:
    stage: build
    image: openjdk:11
    script:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Check with Gradle
        run: ./gradlew check -x test

  unit_tests:
    stage: unit_tests
    image: openjdk:11
    script:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew test --tests CalculatorTest

  system_test:
    stage: system_test
    image: openjdk:11
    script:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run system tests
        run: ./gradlew test --tests "api.*"