name: CI

on:
  push:
    branches:
      - master

stages:
  - build
  - unit_tests
  - system_test
  - metrics

jobs:
  build:
    stage: build
    image: openjdk:11
    script:
      - ./gradlew build -x test
      - ./gradlew check -x test

  unit_tests:
    stage: unit_tests
    image: openjdk:11
    script:
      - ./gradlew test --tests CalculatorTest

  system_test:
    stage: system_test
    image: openjdk:11
    script:
      - ./gradlew test --tests "api.*"